version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "users-sam-deployment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l2f4k3znahtc"
s3_prefix = "users-samt"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
